services:
  mailer:
    container_name: mailer_ms
    build:
      context: .
      dockerfile: dev.dockerfile
    env_file:
      - ./.env
    ports:
      - 4545:4545
    volumes:
      - .:/app
      - db:/app/data
volumes:
  db: